name: Nuget-Build-Test-Publish

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    # Schedule run every Sunday
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build, test and upload nuget package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use latest nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'

      - name: GetVersionNumer
        if: ${{ github.event_name == 'push' }}
        working-directory: ./submodule/snowball
        run: |
          git fetch --tags
          echo "NUGET_PAKCAGE_VERSION=$(git describe --tags|cut -c2-)" >> $GITHUB_ENV

      - name: GetDevVersionNumer
        if: ${{ github.event_name != 'push' }}
        working-directory: ./submodule/snowball
        run: |
          git fetch --tags
          echo "NUGET_PAKCAGE_VERSION=$(git describe --tags|cut -c2-)-dev-${{ github.sha }}" >> $GITHUB_ENV

      - name: Save snk key file for assemblt signing
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: libstemmer.net.snk
          fileDir: ./src/libstemmer.net
          encodedString: ${{ secrets.LIBSTEMMER_NET_SNK }}

      - name: Build and test Snowball for csharp
        working-directory: ./submodule/snowball
        run: make check_csharp

      - name: Build the nuget package
        working-directory: ./src/libstemmer.net
        run: |
          dotnet build \
            libstemmer.net.csproj \
            -c Release
          nuget pack \
            libstemmer.net.nuspec \
            -OutputDirectory ${{ github.workspace }} \
            -Version ${{ env.NUGET_PAKCAGE_VERSION }}

      - name: Test the nuget package
        working-directory: ./src/libstemmer.net.unittest
        run: |
          dotnet restore
          mkdir package
          nuget add \
            "${{ github.workspace }}/libstemmer.net.${{ env.NUGET_PAKCAGE_VERSION }}.nupkg" \
            -Source ./packages
          dotnet add \
            package libstemmer.net \
            --prerelease \
            -s ./packages
          dotnet test

      - name: Upload nuget package
        uses: actions/upload-artifact@v3
        with:
          name: nuget package
          path: ${{ github.workspace }}/*.nupkg