name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: GetVersion
        working-directory: ./submodule/snowball
        run: |
          git fetch --tags
          echo "NUGET_PAKCAGE_VERSION=$(git describe --tags|cut -c2-)" >> $GITHUB_ENV

      - name: Build and test Snowball for csharp
        working-directory: ./submodule/snowball
        run: make check_csharp

      - name: Build the nuget package
        working-directory: ./src/libstemmer.net
        run: |
          dotnet pack \
            libstemmer.net.csproj \
            -c Release
          nuget pack \
            libstemmer.net.nuspec \
            -OutputDirectory ${{ github.workspace }} \
            -Version ${{ nuget.package.version }}

      - name: Upload nuget package
        uses: actions/upload-artifact@v3
        with:
          name: nuget package
          path: ${{ github.workspace }}/**/*.nupkg