name: Nuget-Build-Test-Publish

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: GetVersionNumer
        if: ${{ github.event_name == 'push' }}
        working-directory: ./submodule/snowball
        run: |
          git fetch --tags
          echo "NUGET_PAKCAGE_VERSION=$(git describe --tags|cut -c2-)" >> $GITHUB_ENV
          echo ${{ github.base.ref }}

      - name: GetDevVersionNumer
        if: ${{ github.event_name != 'push' }}
        working-directory: ./submodule/snowball
        run: |
          git fetch --tags
          echo "NUGET_PAKCAGE_VERSION=$(git describe --tags|cut -c2-)-dev-${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and test Snowball for csharp
        working-directory: ./submodule/snowball
        run: make check_csharp

      - name: Build the nuget package
        working-directory: ./src/libstemmer.net
        run: |
          dotnet build \
            libstemmer.net.csproj \
            -c Release
          nuget pack \
            libstemmer.net.nuspec \
            -OutputDirectory ${{ github.workspace }} \
            -Version ${{ env.NUGET_PAKCAGE_VERSION }}

      - name: Test the nuget package
        working-directory: ./src/libstemmer.net.unittest
        run: |
          dotnet restore
          mkdir package
          nuget add \
            "${{ github.workspace }}/libstemmer.net.${{ env.NUGET_PAKCAGE_VERSION }}.nupkg" \
            -Source ./packages
          dotnet add \
            package libstemmer.net \
            -s ./packages
          dotnet test

      - name: Upload nuget package
        uses: actions/upload-artifact@v3
        with:
          name: nuget package
          path: ${{ github.workspace }}/**/*.nupkg